version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - 80
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    env_file:
      - app.env

  rev-proxy:
    container_name: rev-proxy
    build: ./rev-proxy
    volumes:
      - ./rev-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /srv/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    extra_hosts:
      - "host.docker.internal:172.100.0.3"
    env_file:
      - app.env
    tty: true

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
