version: "3"
#volumes:
#  node_modules:

services:

  rev-proxy:
    container_name: rev-proxy
    build: 
      context: ./rev-proxy
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    env_file:
      - .env
    tty: true
    networks:
      default:
        ipv4_address: ${REV_PROXY_ADDRESS}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - FRONTEND_HOME=${FRONTEND_HOME}
    #expose:
    #  - 80
    volumes:
      - ./frontend:${FRONTEND_HOME}
      #- node_modules:${FRONTEND_HOME}/node_modules
      - ${FRONTEND_HOME}/node_modules/
      - ./projects/:${FRONTEND_HOME}/src/projects/
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${FRONTEND_ADDRESS}

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        - BACKEND_HOME=${BACKEND_HOME}
    #expose:
    #  - "80"
    volumes:
      - ./backend:${BACKEND_HOME}
      - ./projects:${BACKEND_HOME}/projects
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${BACKEND_ADDRESS}

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      default:
        ipv4_address: ${REDIS_ADDRESS}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      default:
        ipv4_address: ${MONGODB_ADDRESS}

  #jupyter:
  #  build:
  #    context: ./jupyter
  #  container_name: jupyter
  #  volumes:
  #    - ./jupyter:/home/jovyan/work
  #  ports:
  #    - "8888:8888"
  #  networks:
  #    default:
  #      ipv4_address: ${JUPYTER_ADDRESS}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
