version: "3"
services:

  rev-proxy:
    container_name: rev-proxy
    build: 
      context: ./rev-proxy
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - /srv/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    env_file:
      - .env
    tty: true
    networks:
      default:
        ipv4_address: ${REV_PROXY_ADDRESS}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - FRONTEND_HOME=${FRONTEND_HOME}
    expose:
      - 80
    volumes:
      - ./frontend:${FRONTEND_HOME}
      - ${FRONTEND_HOME}/node_modules
      - ./projects:${FRONTEND_HOME}/src/projects
        #working_dir: ${FRONTEND_HOME}
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${FRONTEND_ADDRESS}

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        - BACKEND_HOME=${BACKEND_HOME}
    expose:
      - 80
    volumes:
      - ./backend:${BACKEND_HOME}
      - ./projects:${BACKEND_HOME}/projects
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${BACKEND_ADDRESS}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - 27017
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      default:
        ipv4_address: ${MONGODB_ADDRESS}

        #jupyter:
        #  image: jupyter/scipy-notebook
        #  container_name: jupyter
        #  ports:
        #    - "80:8888"
        #  volumes:
        #    - ./:/home/jovyan/work
        #  environment:
        #    - PASSWORD=${JUPYTER_NB_PASSWORD}
        #  networks:
        #    default:
        #      ipv4_address: ${BACKEND_ADDRESS}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
