version: "3"
services:

  rev-proxy:
    container_name: rev-proxy
    build: 
      context: ./rev-proxy
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - /srv/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    env_file:
      - .env
    tty: true
    networks:
      default:
        ipv4_address: 172.100.0.2

  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - 80
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      default:
        ipv4_address: 172.100.0.3

        #backend:
        #  container_name: backend
        #  build: ./backend
        #  expose:
        #    - 80
        #  volumes:
        #    - ./backend:/app
        #  stdin_open: true
        #  tty: true
        #  env_file:
        #    - app.env
        #  networks:
        #    default:
        #      ipv4_address: 172.100.0.4

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
