#!/bin/bash

if [ "$1" = "init" ]; then
    TUTTI_NEWGRP=0
    if [ "$(uname -s | cut -b 1-5)" == "Linux" ]; then
        if [ ! $(getent group docker) ]; then
            sudo groupadd docker
            sudo gpasswd -a $USER docker
            sudo systemctl restart docker
            sudo chmod +x /usr/local/bin/docker-compose
            TUTTI_NEWGRP=1
            echo '' >> ~/.bashrc
            echo '# Tutti envs' >> ~/.bashrc
            echo 'export HOST_WEBAPI_ADDRESS=172.0.0.1' >> ~/.bashrc
            source ~/.bashrc
            newgrp docker
        fi
    fi
    if [ $TUTTI_NEWGRP = 1 ]; then
        echo -e "\033[1;33mWarning: You have logged out from docker user group. You may need to log out once (or run 'newgrp docker') for normal Tutti functionality.\033[0m"
    fi

elif [ "$1" = "build" ]; then
    docker-compose build

elif [ "$1" = "start" ]; then
    find projects/.defaultproject -type f -print0 | xargs -0 chmod 644

    if [ -e .host_api.pid ] && [ -n "$(ps -p `cat .host_api.pid` -o pid=)" ]; then
        echo "Tutti is already started."
    else
        python3 host_api.py >> ./logs/host_api.log 2>&1 &
        echo $! > .host_api.pid
    fi

    docker-compose up -d

elif [ "$1" = "stop" ]; then
    docker-compose down
    TUTTI_HOST_PID=`cat .host_api.pid`
    kill -SIGTERM $TUTTI_HOST_PID

elif [ "$1" = "kill" ]; then
    docker-compose kill
    TUTTI_HOST_PID=`cat .host_api.pid`
    kill $TUTTI_HOST_PID

elif [ "$1" = "log" ]; then
    if [ "$2" = "host" ]; then
        less +F -K ./logs/host_api.log
    else
        docker-compose logs --tail="50" -f $2
    fi
else
    echo "
    usage: ./tutti [init|start|stop|kill|log] [container]
    
    init  ... Initialize Tutti environment
    build ... Build Tutti environment (i.e., docker-compose build)
    start ... Start containers and host web server
    stop  ... Stop containers and host web server
    kill  ... Kill containers and host web server
    log   ... Monitor output logs of a specified container (Ctrl+C to abort)
    "

fi
