FROM python:3.9-buster

ARG BACKEND_HOME
WORKDIR $BACKEND_HOME

#COPY requirements.txt ./
#
#RUN pip install --no-cache-dir -r requirements.txt
#
#CMD ["python", "-m", "ducts", "server", "start"]

CMD ["/bin/bash"]
